### ISSUE TITLE
[COMIENZA AQUÍ] Descripción de updates

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/frenalacurvamx#1]
Echa un ojo a los issues [del tablero](https://github.com/CodeandoMexico/frenalacurvamx/projects/1) y solicita que se te asigne el que quieras trabajar.

#### Update general de la landing page (24/04/2020)

La imagen a contnuación ilustra un poco los bloques que esperan ser añadidos (3). Cada bloque será separado en un issue distinto (se hará referencia a ellos) y las contribuciones podrán ser enviadas a través de Pull Requests (siguiendo el git flow tradicional).

![photo5172438143050295371](https://user-images.githubusercontent.com/8453749/77466022-3ac70200-6dcf-11ea-9cf9-167cbafb1dbc.jpg)

Los issues son:
- Añadir bloque de información verificada: https://github.com/CodeandoMexico/frenalacurvamx/issues/2
- Añadir bloque de iniciativas: https://github.com/CodeandoMexico/frenalacurvamx/issues/3
- Añadir bloque de Telegram: https://github.com/CodeandoMexico/frenalacurvamx/issues/4

**Comment by roxdelafuente** [comment]
Aquí pueden ver la info que se tiene de FrenaLaCurva México, por si quieren agregar algón otro elemento que sea útil para el sitio: https://bit.ly/frenalacurvamxiniciativas

**Comment by RodolfoFerro** [comment]
Mudamos las conversaciones de operación con la página a: https://t.me/FLCLanding
