### ISSUE TITLE
Añadir bloque de información verificada

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/frenalacurvamx#2]
Especificaciones:
- Cambiar la sección de "Cuidarnos | Aprender | Compartir" por un bloque de "Información verificada" como se muestra en el mockup: https://github.com/CodeandoMexico/frenalacurvamx/issues/1
- Para las tres imágenes que se requieren, especificar en este issue las dimensiones. El equipo de mexico.frenalacurva.net puede proporcionar las imágenes, diseños y links.
- Ya hay una clase de CSS llamada `section-feature-grey` que puede ayudar para ir alternando los fondos.

**Comment by mxcoder** [comment]
Hola @RodolfoFerro , como el diseño no es lo mío creo que podría ayudar con esta tarea siempre y cuando se provean las imágenes, sabes a quién le puedo preguntar por ellas?

**Comment by RodolfoFerro** [comment]
Claro, deja hago el conecte con @roxdelafuente. Rox nos puede apoyar con todo el tema de diseño e imagen. :)

**Comment by roxdelafuente** [comment]
Hola! @mxcoder 
Yo te puedo ayudar con las imágenes, algún tamaño o formato en especial? 

El título del bloque podría ser: **Noticias e Información ofical sobre el COVID-19**, abierto a sugerencias. 

Los links a donde te debería de llevar estos 3 botones serían: 
1. Animal Político, noticias verificadas: https://www.animalpolitico.com/noticias-coronavirus-covid-2019-verificacion/
2. Mapa en tiempo real del coronavirus en México: https://www.eleconomista.com.mx/politica/Mapa-del-coronavirus-Covid-19-lo-que-usted-debe-saber-sobre-el-coronavirus-en-Mexico-y-a-escala-global-20200309-0089.html  (si conocen otro mapa más lindo, bienvenido!)
3. Información oficial del Gobierno de México: https://coronavirus.gob.mx/

**Comment by mxcoder** [comment]
Pues respecto al tamaño y formato, si gustas puedes compartirlas en un formato grande, y de ahi vamos probando distintas optimizaciones, para que al final no queden tan grandes ni pesadas.

**Comment by roxdelafuente** [comment]
Mira si quieres pongamos los logos: 

- https://www.animalpolitico.com/wp-content/themes/animalpolitico-2019/static/assets/logo.svg
- https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/COVID-19_Outbreak_Cases_in_Mexico.svg/1200px-COVID-19_Outbreak_Cases_in_Mexico.svg.png
- https://coronavirus.gob.mx/wp-content/uploads/2020/03/logoheader.svg

y debajo el titulo/pequeña descripción... te sirve así?

**Comment by mxcoder** [comment]
Si! en SVG es excelente, gracias :)

**Comment by RodolfoFerro** [comment]
Hola @mxcoder, ¿hay algo en lo que pueda ayudar con esto?

**Comment by mxcoder** [comment]
Hola @RodolfoFerro , perdona la tardanza, ya está el PR.

**Comment by RodolfoFerro** [comment]
Va que va, lo reviso. 🙂👌

**Comment by RodolfoFerro** [comment]
Estoy subiendo los cambios, ¡buenísimo, gracias! 🎉 @mxcoder
