### ISSUE TITLE
Añadir bloque de iniciativas

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/frenalacurvamx#3]
Especificaciones:
- Añadir una sección de "Conoce las iniciativas" como se muestra en el mockup: https://github.com/CodeandoMexico/frenalacurvamx/issues/1
- Para las imágenes que se requieren, especificar en este issue las dimensiones. El equipo de mexico.frenalacurva.net puede proporcionar las imágenes y diseños.
- Para las iniciativas a desplegar, el equipo de mexico.frenalacurva.net puede proporcionar las que se vayan a poner, así como los links a las mismas y al documento que se menciona en la sección.
- **Este bloque tiene una propuesta de diseño en el mockup ya mencionado, pero en realidad es un bloque abierto a sugerencias.**
- Ya hay una clase de CSS llamada `section-feature-grey` que puede ayudar para ir alternando los fondos de las secciones.

**Comment by roxdelafuente** [comment]
En el slide 13, de este doc viene la info: https://docs.google.com/presentation/d/1hzj-ZyHghMu2C_mPNfxCtnvETOA2aASbT26HWeGGxIM/edit#slide=id.g71e0fcc168_29_0

**Comment by roxdelafuente** [comment]
Si necesitan otro tamaño, formato please me avisan. 

![FLC_Cuidados_v02](https://user-images.githubusercontent.com/62305074/77477530-1f192700-6de2-11ea-8dbe-b3203be45054.png)
![FLC_Cultura_v02](https://user-images.githubusercontent.com/62305074/77477556-2b9d7f80-6de2-11ea-8620-bc0bd71b063c.png)
![FLC_Educacion_v02](https://user-images.githubusercontent.com/62305074/77477558-2c361600-6de2-11ea-8209-6392ca534212.png)
![FLC_Trabajo_v02](https://user-images.githubusercontent.com/62305074/77477567-2cceac80-6de2-11ea-8a0c-996fcfbd44e2.png)

**Comment by tavorazo** [comment]
Hola, podemos ayudar con este bloque, saludos

**Comment by RodolfoFerro** [comment]
¡Zaz, te asigno el issue @tavorazo !

**Comment by RodolfoFerro** [comment]
Hola @tavorazo, ¿hay algo más en lo que pueda ayudar con esto?

**Comment by tavorazo** [comment]
No, justo estaba haciendo el push. Trataba de hacer algo mucho más detallado pero me tarde más de lo pensado. Se me atravesó algo de trabajo

**Comment by RodolfoFerro** [comment]
¡Va que va! Y zaz, aquí ando pendiente por cualquier cosa que haga falta. 👌

**Comment by tavorazo** [comment]
Te escribí vía slack
