### ISSUE TITLE
Añadir bloque de Telegram

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/frenalacurvamx#4]
Especificaciones:
- Cambiar la sección de "Infórmate" (con el Twitter) como se muestra en el mockup: https://github.com/CodeandoMexico/frenalacurvamx/issues/1
- Para las imágenes que se requieren, especificar en este issue las dimensiones. El equipo de mexico.frenalacurva.net puede proporcionar las imágenes y diseños.
- El URL al chat de Telegram es el siguiente: https://t.me/frenalacurvamx  
- **Este bloque tiene una propuesta de diseño en el mockup ya mencionado, pero en realidad es un bloque abierto a sugerencias.** Puede en realidad dejarse de un lado el link al Telegram y del otro a Twitter o hacer una propuesta propia.
- Ya hay una clase de CSS llamada `section-feature-grey` que puede ayudar para ir alternando los fondos de las secciones.

**Comment by roxdelafuente** [comment]
Podríamos poner de texto: 

¿Te quieres sumar?
Búscanos en Telegram.
- CHAT: https://t.me/frenalacurvamxchat  
- CANAL DE DIFUSIÓN: https://t.me/frenalacurvamx 

y no se si agregar un botón de sharethis a las redes con esto:

Comparte la guía con los pasos de cómo te puedes sumar y apoyar: bit.ly/frenalacurvamxiniciativas

**Comment by MrCesar107** [comment]
Hola @RodolfoFerro yo puedo ayudarles con este issue

**Comment by RodolfoFerro** [comment]
Zaz, te lo asignamos @MrCesar107. :)

**Comment by RodolfoFerro** [comment]
Hola @MrCesar107, ¿hay algo en lo que pueda ayudar con esto?

**Comment by MrCesar107** [comment]
Hola @RodolfoFerro, solo necesito las imagenes que se piensan usar para este bloque

**Comment by roxdelafuente** [comment]
@MrCesar107 Hola! Yo te puedo apoyar con eso, si quieres el bloque puede ser en color rojo para que se vea distinto al anterior, no se que opines... donde viene telegram podríamos poner este gif: https://media.giphy.com/media/ZcdZ7ldgeIhfesqA6E/giphy.gif  

o si no, aca va otro en svg: https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Telegram_2019_Logo.svg/1024px-Telegram_2019_Logo.svg.png

y deja armo un icono para la guía y te las paso en un rato más. tienes alguna idea/sugerencoa?

**Comment by MrCesar107** [comment]
@roxdelafuente yo opino que en caso de que el bloque de telegram vayamos alternando el fondo a rojo, blanco, rojo, blanco para poder tener un mismo look and feel en la pagina, quizá podríamos alternar rojo a dos secciones luego blanco otras dos secciones y así, no se que opines. Las imágenes se ven bien, me gusta más el gif.

**Comment by roxdelafuente** [comment]
Totalmente de acuerdo.

**Comment by MrCesar107** [comment]
si gustas podemos hablar por slack

**Comment by MrCesar107** [comment]
Hola, lamento la tardanza con este issue. Aquí dejo el PR correspondiente
https://github.com/CodeandoMexico/frenalacurvamx/pull/10
