### ISSUE TITLE
Actualizar src del mapa en la sección de "Conoce los medios oficiales..."

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/frenalacurvamx#8]
Cambiar el source del mapa actual (EL ECONOMISTA) de la sección "Conoce los medios oficiales en donde podrás encontrar información verificada" por: https://covid19enmexico.com/

- La imagen en SVG del mapa puede quedarse, sólo se debe actualizar el label del mapa y el src del URL.

**Comment by GeraAlcantara** [comment]
Hola 👋 @RodolfoFerro 

Yo puedo tomar este issue en un rato te mando el PR

Saludos
